// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using GestaoFinanceiraApi.Data.Context;

namespace GestaoFinanceiraApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("GestaoFinanceiraApi.Entity.Usuario", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");

                b.Property<string>("Email").IsRequired().HasColumnType("nvarchar(max)");

                b.Property<bool>("IsAdmin").HasColumnType("bit");

                b.Property<string>("Nome").IsRequired().HasColumnType("nvarchar(max)");

                b.Property<string>("SenhaHash").IsRequired().HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Usuarios");
            });

            modelBuilder.Entity("GestaoFinanceiraApi.Entity.Gastos", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");

                b.Property<string>("Categoria").IsRequired().HasColumnType("nvarchar(max)");

                b.Property<DateTime>("DataGasto").HasColumnType("datetime2");

                b.Property<string>("Descricao").IsRequired().HasColumnType("nvarchar(max)");

                b.Property<string>("Pagamento").IsRequired().HasColumnType("nvarchar(max)");

                b.Property<decimal>("Valor").HasColumnType("decimal(18,2)");

                b.Property<long>("UsuarioId").HasColumnType("bigint");

                b.HasKey("Id");

                b.ToTable("Gastos");
            });

            modelBuilder.Entity("GestaoFinanceiraApi.Entity.Ganhos", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");

                b.Property<string>("Categoria").IsRequired().HasColumnType("nvarchar(max)");

                b.Property<DateTime>("DataGanho").HasColumnType("datetime2");

                b.Property<string>("Descricao").IsRequired().HasColumnType("nvarchar(max)");

                b.Property<string>("Pagamento").IsRequired().HasColumnType("nvarchar(max)");

                b.Property<decimal>("Valor").HasColumnType("decimal(18,2)");

                b.Property<long>("UsuarioId").HasColumnType("bigint");

                b.HasKey("Id");

                b.ToTable("Ganhos");
            });

            modelBuilder.Entity("GestaoFinanceiraApi.Entity.Investimento", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");

                b.Property<string>("Categoria").IsRequired().HasColumnType("nvarchar(max)");

                b.Property<DateTime>("DataAplicacao").HasColumnType("datetime2");

                b.Property<string>("Descricao").IsRequired().HasColumnType("nvarchar(max)");

                b.Property<decimal>("ValorAplicado").HasColumnType("decimal(18,2)");

                b.Property<long>("UsuarioId").HasColumnType("bigint");

                b.HasKey("Id");

                b.ToTable("Investimentos");
            });
        }
    }
}
